name: CI

on:
- push
- pull_request

jobs:
  host:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        ruby:
        - truffleruby-head

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: sudo apt install ragel
        if: ${{ startsWith(matrix.os, 'ubuntu') }}

      - run: brew install ragel
        if: ${{ startsWith(matrix.os, 'macos') }}

      - run: bundle install

      - run: rake compile

      - run: rake test

      - run: rake build

      - run: gem install pkg/*.gem

